#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Styling, testing and building your portfolio before committing.'

# Check Prettier standards
# echo '🎨 Prettifying your code.'
# yarn check-format ||
# (
#     echo '❌ 🎨 Prettier Check Failed. Run npm run format, add changes and try committing again. 🎨 ❌';
#     false;
# )

# Check ESLint Standards
echo '🤵 Checkign ESLint standards.'
yarn check-lint ||
(
        echo '🤵 ❌ ESLint Check Failed. Make the changes required above and try committing again. ❌ 🤵'
        false;
)

# # Check tsconfig standards
echo '⌨️ Type checking.'
yarn check-types ||
(
    echo '❌ ⌨️ Failed Type check. Make the changes required above and try committing again. ⌨️ ❌'
    false;
)

# If everything passes... Now we can commit
echo '✅ ✅Your checked-in code looks good. Commiting... ✅ ✅'
